<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>RssiCalibration.Cli</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Argus\VisiLib.Args.csproj" />
    <ProjectReference Include="..\RssiCalibration.Core\RssiCalibration.Core.csproj" />
    <ProjectReference Include="..\RssiCalibration.Data\RssiCalibration.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\data\**" CopyToOutputDirectory="PreserveNewest" LinkBase="data" />
  </ItemGroup>
</Project>
